project_id = "myqrydgbrxhrjkrvkgqq"

[functions.send-contact-email]
verify_jwt = false

[functions.asaas-checkout]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-manage-subscription]
verify_jwt = false

[functions.increment-page-view]
verify_jwt = false

[functions.add-domain]
verify_jwt = false

[functions.verify-domain]
verify_jwt = false

[functions.remove-domain]
verify_jwt = false

[functions.resolve-custom-domain]
verify_jwt = false
